version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: orders-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:7
    container_name: products-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./product-service.products.json:/docker-entrypoint-initdb.d/product-service.products.json:ro

volumes:
  pgdata:
  mongo_data:
